<div id="main">

	<div class="title"> Gallery </div>

	<div id="galery">
	
		<!-- Pierwszy rząd -->
	
		<div class="img first_gal">
			<a href="/galery/8.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/8.JPG" alt="" width="170" height="128"                        
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">When Loading Lorries in the ice, make sure you don’t slip off the trailer !!!!!</div>
		</div>
		
		<div class="img">
			<a href="/galery/9.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/9.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">When Loading Lorries in the ice, make sure you don’t slip off the trailer !!!!!</div>
		</div>
		
		<div class="img">
			<a href="/galery/10.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/10.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">When Loading Lorries in the ice, make sure you don’t slip off the trailer !!!!!</div>
		</div>
	
		<!-- Drugi rząd -->	
	
		<div class="img first_gal">
			<a href="/galery/1.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/1.JPG" alt="" width="170" height="128"                        
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
		
		<div class="img">
			<a href="/galery/2.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/2.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
		
		<div class="img">
			<a href="/galery/3.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/3.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
		
		<!-- Trzeci rząd -->	
	
		<div class="img first_gal">
			<a href="/galery/4.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/4.JPG" alt="" width="170" height="128"                        
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
		
		<div class="img">
			<a href="/galery/6.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/6.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
		
		<div class="img">
			<a href="/galery/7.JPG" rel="lightbox">
		    	<img class="galery" src="/galery/thumbs/7.JPG" alt="" width="170" height="128"                         
		        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
		    </a> 
		    <div class="click">Click Image to Enlarge</div>
		</div>
				
	</div>

</div>