<div id="main">

	<div class="title"> Gallery </div>

	<div class="img">
		<a href="/galery/thumbs/1.jpg" rel="lightbox">
	    	<img class="galery" src="/galery/1.jpg" alt="" width="170" height="128"                         
	        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
	        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
	    </a> 
	    <div class="click">Click Image to Enlarge</div>
	</div>
	
	
	

</div>