<script type="text/javascript">
		refreshCss();						
</script>';

<div id="main">

	<div class = 'lastarrival'>				
		<div class = 'lastarrivalstitle'>Latest Arrivals</div>				
		<div class="lastarrivalsphotos">
			<?php echo $this->lastMachines($this->lm)?>
		</div>
		<div class="lastarrivalsummary">Click image to see more details</div>					
	</div>			
						
	
	<br>
	<div class="wysrodkowanie">
		<p>Centrally located between the M1 & M6, J.A. Bloor Agriservices prides itself on selling and hiring high quality
		tractors and a selection of farm machinery at highly competitive prices.</p>

		<p>With a lifelong interest in farm machinery and still actively farming, Jason Bloor provides a hands-on, personal
		practical service along with years of experience and knowledge to understand his customers' needs.</p>

		<p>Please feel free to call me anytime on mobile 07860 95 95 92</p>


		<center> 	<b><font color="red">NEW</font></b>
			 	<a class="galerylink" href="/index/ketlec/">To see our new Keltec round bale slice demonstration click this link</a> 
				<b><font color="red">NEW</font></b>
		</center>
		</br>		
		<center> 	<b><font color="red">NEW</font></b>
			 	<a class="galerylink" href="/index/galery/">To see our gallery click this link</a> 
				<b><font color="red">NEW</font></b>
		</center>
	</div>
		
		
		
		<img style="position: relative; left: 200px; top: -15px;" src="/images/overton.jpg">
		


<br />
		
		
		<center>
			<?php
				$counter = new Model_Counter();
        		$counter->loadHits();
        		echo $counter->getHits(); 
			?>
			<!-- (c) 2006 DarmoweLiczniki.pl - Największy wybór w sieci -->
<!--
			<script language="javascript1.2" type="text/javascript">
			document.write('<scr'+'ipt src="http://hit.darmoweliczniki.pl/?id=33932&cach='+(new Date()).getTime()+'" language="javascript"></scr'+'ipt>');
			</script>
-->
		</center>
</div>