<div id="main">
	
	<div class="title"> Demonstration of Keltec </div>

	<div class="img" style="margin-left: 100px;">
		<a href="/galery/ketlec2.JPG" rel="lightbox" title="">
	    	<img class="galery" src="/galery/thumbs/ketlec2.JPG" alt="" width="170" height="128"                         
	        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
	        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
	    </a> 
	</div>

	<div class="img">
		<a href="/galery/ketlec3.JPG" rel="lightbox" title="">
	    	<img class="galery" src="/galery/thumbs/ketlec3.JPG" alt="" width="170" height="128"                         
	        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
	        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
	    </a> 
	</div>

	<div class="img">
		<a href="/galery/ketlec4.JPG" rel="lightbox" title="">
	    	<img class="galery" src="/galery/thumbs/ketlec4.JPG" alt="" width="170" height="128"                         
	        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
	        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
	    </a> 
	</div>

	<div class="img" style="margin-left: 380px;">
		<a href="/galery/ketlec1.JPG" rel="lightbox" title="">
	    	<img class="galery" src="/galery/thumbs/ketlec1.JPG" alt="" width="170" height="128"                         
	        onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
	        onmouseout="this.style.opacity=0.85;this.filters.alpha.opacity=85"/>
	    </a> 
	</div>
	
	<div></div>



	<object width="625" height="344" style="height:600px; margin-top: 120px; display: block; margin-left: 280px">
		<param name="movie" value="http://www.youtube.com/v/xPKcz8y_8Pc?hl=pl&fs=1"></param>
		<param name="allowFullScreen" value="true"></param>
		<param name="allowscriptaccess" value="always"></param>
		<embed src="http://www.youtube.com/v/xPKcz8y_8Pc?hl=pl&fs=1" 
			type="application/x-shockwave-flash" allowscriptaccess="always" 
			allowfullscreen="true" width="425" height="344"></embed>
	</object>

</div>

