<div id="smenu">        
	<ul>
    	<li><a class="others" href="/others/machines/main/5/second/24">Loaders</a></li>    	                
        <li><a class="others" href="/others/machines/main/5/second/25">Wheels</a></li>        
        <li><a class="others" href="/others/machines/main/5/second/26">Hedgecutters</a></li>                        
        <li><a class="others" href="/others/machines/main/5/second/27">Attachments</a></li>       
        <li><a class="others" href="/others/machines/main/5/second/28">Sprayers</a></li>       
        <li><a class="others" href="/others/machines/main/5/second/29">Parts</a></li>        
        <li><a class="others" href="/others/machines/main/5/second/30">Others</a></li>
	</ul>
</div>
