<script type="text/javascript">
	//replacing image input to img html tag
	$(document).ready(function() {
		$(".edit-machine-content input[type='image']").each(function(index)
			{
				var src = $(this).attr("src");
				var c = $(this).attr("class");
				$(this).replaceWith( "<img alt='' class='" + c + "' src='" + src + "' >");					
			});
	});
	
</script>

<div class='smain'>

	<div class='stitle'>Edit Machine Details</div>
	<div class='edit-machine-content'>
		<br />
		<?= $this->form?>
	</div>

</div>