<div id="smenu">        
	<ul>
    	<li><a class="plantHire" href="/planthire/machines/main/4/second/18">Mini Digger</a></li>    	                
        <li><a class="plantHire" href="/planthire/machines/main/4/second/19">JCB Loadall</a></li>        
        <li><a class="plantHire" href="/planthire/machines/main/4/second/20">Dumpers & Trailers</a></li>                        
        <li><a class="plantHire" href="/planthire/machines/main/4/second/21">Tractors</a></li>       
        <li><a class="plantHire" href="/planthire/machines/main/4/second/22">Pottinger Europrofi Forage Wagons</a></li>                        
        <li><a class="plantHire" href="/planthire/machines/main/4/second/23">Others</a></li>                
	</ul>
</div>