<div id="smenu">
	<ul>		
		<li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/10">Combines</a></li>		
		<li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/11">Cultivation Equipment</a></li>		
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/12">Balers</a></li>	    
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/13">Mowers</a></li>	                    
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/14">Diet Feeders & Bedders</a></li>	                    
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/15">Muck & Slurry Equipment</a></li>	    
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/16">Trailers</a></li>	                    
	    <li><a class="farmMachinery" href="/farmmachinery/machines/main/3/second/17">Others</a></li>	                    
    </ul>
</div>