<div id="smenu">
            <ul>
                <li><a class="telescopicHandlers" href="/telescopichandlers/machines/main/2/second/6">JCB</a></li>                                
                <li><a class="telescopicHandlers" href="/telescopichandlers/machines/main/2/second/7">Manitou</a></li>                 
                <li><a class="telescopicHandlers" href="/telescopichandlers/machines/main/2/second/8">John Deere</a></li>                                 
                <li><a class="telescopicHandlers" href="/telescopichandlers/machines/main/2/second/9">Others</a></li>                
            </ul>
</div>