<div id="smenu">
            <ul>
                <li><a class="parts" href="/parts/machines/main/6/second/31"> New Parts</a></li>                                
                <li><a class="parts" href="/parts/machines/main/6/second/32"> S/H Parts</a></li>                
                <li><a class="parts" href="/parts/machines/main/6/second/33"> Oils</a></li>                
                <li><a class="parts" href="/parts/machines/main/6/second/34"> Fencing</a></li>                                
            </ul>
</div>