<div id="smenu">
            <ul>
                <li><a class="tractors" href="/tractors/machines/main/1/second/1">John Deere</a></li>                                
                <li><a class="tractors" href="/tractors/machines/main/1/second/2">Case IH</a></li>                
                <li><a class="tractors" href="/tractors/machines/main/1/second/3">Massey Ferguson</a></li>                
                <li><a class="tractors" href="/tractors/machines/main/1/second/4">Ford NH</a></li>                
                <li><a class="tractors" href="/tractors/machines/main/1/second/5">Others</a></li>
                <li><a class="tractors" href="/tractors/machines/main/1/second/51">Combines</a></li>	             
            </ul>
</div>